### ISSUE TITLE
setDeployment does not work when FIDC uses a SNAPSHOT version

### ISSUE THREAD

**Issue by hadimc** [vscheuber/AM-treetool#13]
This is an example of what FIDC returns today as version
VERSION = 7.1.0-2020-15-SNAPSHOT

the script will map DEPLOYMENT to ForgeOps which does not seem to be correct

**Comment by vscheuber** [comment]
Thanks, Hadi! The ID Cloud team changed how they tag their builds. I am working on a fix for this.

**Comment by hadimc** [comment]
Great. Thanks Volker.
