### ISSUE TITLE
Add Support for custom cookie name

### ISSUE THREAD

**Issue by MaximV93** [vscheuber/AM-treetool#6]
Currently the script uses a hardcoded iPlanetDirectoryPro cookie. Would it be possible to add a parameter to specify the name of the cookie and default to iPlanetDirectoryPro if the parameter is not provided?

**Comment by bsebbah** [comment]
Hello,

In the script the default AM cookie name is hardcoded (iPlanetDirectoryPro). 
In https://backstage.forgerock.com/docs/am/6.5/install-guide/#avoid-obvious-defaults you can read:

> 5.1. Avoiding Obvious Defaults
> [...]
> Change the default iPlanetDirectoryPro cookie name both in AM (com.iplanet.am.cookie.name) and in your agent profiles (com.sun.identity.agents.config.cookie.name).

We updated the amtree.sh script by adding a variable with the custom cookie same such as:
AMCOOKIENAME="iPlanetDirectoryPro"
and replaced every instance of the hard coded default cookie name by ${AMCOOKIENAME} and added in the getopts to set it in the command line.

This works great.

Regards,

Ben

**Comment by vscheuber** [comment]
Thank you both, @MaximV93 and @bsebbah for your input! My notification settings were off. I have addressed the session cookie issue in a different, more dynamic way to make amtree.sh fit for ForgeRock Identity Cloud. I am now using the built-in cookie support in curl, which allows shorter commands and different cookie names for every env without even having to know what the cookie name is for that env. Please let me know if this addresses your issue satisfactory.
