### ISSUE TITLE
Can't get AMSESSION because of authenticate url parameters

### ISSUE THREAD

**Issue by bsebbah** [vscheuber/AM-treetool#7]
Hello,

I have seen a regression with the latest version because of this line:
`AMSESSION=$(curl -s -k -X POST -H "Accept-API-Version:resource=1.0" -H "X-Requested-With:XmlHttpRequest" -H "X-OpenAM-Username:$AMADMIN" -H "X-OpenAM-Password:$AMPASSWD" "$AM/json${AREALM}/authenticate?authIndexType=service&authIndexValue=adminconsoleservice" | jq .tokenId | sed -e 's/\"//g')`

AMSESSION was null because the output of the curl was:
{"errorMessage":"Login failure"}

Removing "?authIndexType=service&authIndexValue=adminconsoleservice" in the end of the url did the job.

Regards,

Ben

**Comment by vscheuber** [comment]
Thank you, @bsebbah ! Please check out the latest version. I have changed the login process to work with ForgeRock Identity Cloud and I believe the changes will work for you as well. I now explicitly call the only /authenticate endpoint and let the AM configuration decide what module or tree to use to log the user in. There are still cases where the tool will struggle, namely if you use non-standard callbacks or a tree that asks for more than username and password. But the latest version will work with FIDC and most configurations of on-prem AM.
